#!/bin/bash

echo "Building the encoder"

dtc -O dtb -o bone_eqep0-00A0.dtbo -b 0 -@ bone_eqep0.dts
dtc -O dtb -o bone_eqep1-00A0.dtbo -b 0 -@ bone_eqep1.dts
dtc -O dtb -o bone_eqep2-00A0.dtbo -b 0 -@ bone_eqep2.dts
dtc -O dtb -o bone_eqep2b-00A0.dtbo -b 0 -@ bone_eqep2b.dts

cp bone_eqep0-00A0.dtbo /lib/firmware
cp bone_eqep1-00A0.dtbo /lib/firmware
cp bone_eqep2-00A0.dtbo /lib/firmware
cp bone_eqep2b-00A0.dtbo /lib/firmware

export SLOTS=/sys/devices/bone_capemgr.*/slots
echo bone_eqep2b > $SLOTS
cat $SLOTS
